CREATE TABLE EMPLOYEE(
    EMP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMPNAME VARCHAR(50),
    GENDER ENUM ('M','F','O'),
    GRADE_LEVEL VARCHAR(2),
    DOJ DATE,
    DESIGNATION VARCHAR(50),
    EMPTYPE ENUM('FULL-TIME','PART-TIME','CONTRACT'),
    EMPSTATUS ENUM('ACIVE','INACTIVE'),
    PROB_PERIOD INT,
    PROB_COMP_DATE DATE,
    TRAIN_PERIOD INT,
    CONTRACT_END DATE,
    SERV_PERIOD INT,
    ISGM TINYINT(1),
    ISEXPAT TINYINT(1),
    RELEASE_DATE DATE,
    USERID VARCHAR(20) UNIQUE,
    EMAIL VARCHAR(50) UNIQUE,
    BRANCH VARCHAR(50),
    OFFICE VARCHAR(50),
    CTC DECIMAL,
    WORKSTATIONID VARCHAR(4) UNIQUE,
    EMP_ROLE VARCHAR(4),
    ATTENDANCE INT,
    LEAVE_TAKEN INT,
    LEAVE_AVAILABLE INT,
    HIKE DECIMAL,
    PROJ_ID REFERENCES PROJECT(PROJ_ID),
    GRP_ID REFERENCES TEAM(GRP_ID)
);

CREATE TABLE TEAM(
    GRP_ID INT PRIMARY KEY AUTO_INCREMENT,
    GM VARCHAR(50)
    DEPT_ID REFERENCES DEPARTMENT(DEPT_ID),
    PROJ_ID REFERENCES PROJECT(PROJ_ID),
)

CREATE TABLE DEPARTMENT(
    DEPT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(30),
    HOD VARCHAR(50)
);

CREATE TABLE PROJECT(
    PROJ_ID INT PRIMARY KEY AUTO_INCREMENT,
    PM VARCHAR(50)
);

CREATE TABLE EMPLOYEEDETAILS(
    EMP_DET_ID INT PRIMARY KEY AUTO_INCREMENT ON DELETE CASCADE,
    PROFILE_PIC_DOC VARCHAR(255),
    PERMA_ADDR VARCHAR(100),
    PRIMARY_CONTACTNO VARCHAR(10),
    EMERGENCY_CONTACTNO VARCHAR(10),
    ADDR_PROOF_DOC VARCHAR(50),
    EMAIL_ID VARCHAR(30),
    DOB DATE,
    PRESENT_ADDR VARCHAR(100),
    NATIONALITY VARCHAR(20),
    BLOOD_GRP VARCHAR(3),
    DIFF_ABLED VARCHAR(3) CHECK CONSTRAINT (DIFF_ABLED IN ('YES','NO')),
    DIFF_ABLED_DOC VARCHAR(50),
    EMP_ID INT REFERENCES EMPDETAILS(EMP_ID)
);

CREATE TABLE FAMILYDETAILS(
    FAMILY_ID INT PRIMARY KEY AUTOINCREMENT ON DELETE CASCADE,
    MARITAL_STAT ENUM ('SINGLE','MARRIED','DIVORCED','WIDOWED'),
    RELATION ENUM('SPOUSE', 'FATHER','MOTHER','BROTHER','SISTER','CHILD'),
    FAM_NAME VARCHAR(30),
    DOB DATE,
    OCCUPATION VARCHAR(30),
    CONTACTNO VARCHAR(10),
    MED_INSC ENUM('Y','N'),
    EMP_ID INT REFERENCES EMPDETAILS(EMP_ID)
);

CREATE TABLE EMPLOYEEDOCUMENTS(
    EMP_DOC_ID INT AUTO_INCREMENT ON DELETE CASCADE,
    PANCARD_DOC VARCHAR(50),
    PANCARDNO VARCHAR(10),
    UAN_DOC VARCHAR(50),
    PRAN_DOC VARCHAR(50),
    ADHAAR_DOC VARCHAR(50),
    ADHAARNO VARCHAR(12),
    PASSPORT_DOC VARCHAR(50),
    PASSPORTNO VARACHAR(10),
    PLACE_OF_ISSUE VARCHAR(20),
    DATE_OF_ISSUE DATE,
    DATE_OF_EXPIRY DATE,
    BANK_NAME VARCHAR(30),
    ACC_NO DOUBLE,
    IFSC VARCHAR(12),
    PRIMARY_ACC ENUM('Y','N'),
    IS_ACTIVE ENUM('Y','N'),
    EMP_ID INT REFERENCES EMPDETAILS(EMP_ID)

);

CREATE TABLE QUALIFICATION_DETAILS(
    QD_ID INT AUTO_INCREMENT ON DELETE CASCADE,
    HIGHEST_QUAL VARCHAR(50),
    HIGHEST_QUAL_DOC VARCHAR(50),
    _10TH_CERT VARCHAR(255),
    _12TH_CERT VARCHAR(255),
    EMP_ID INT REFERENCES EMPDETAILS(EMP_ID)

);

CREATE TABLE PROF_DETAILS(
    PROF_DEL_ID INT AUTO_INCREMENT ON DELETE CASCADE,
    NAME_OF_PREV_ORG VARCHAR(50),
    DESIGNATION VARCHAR(30),
    FROM_DATE DATE,
    TO_DATE DATE,
    RELEASE_LETTER_DOC VARCHAR(50),
    EXPERIENCE_CERT VARCHAR(50),
    REPORTING_STRUC VARCHAR(20),
    PROF_BODIES_MEMBER VARCHAR(50),
    SOCIAL_BODIES_MEMBER VARCHAR(50),
    EMP_ID INT REFERENCES EMPDETAILS(EMP_ID)

)


